version: "3.1"

services:
  db:
    container_name: mongo
    image: mongo:4.2.10-bionic
    ports:
      - "27017:27017"

  zookeeper:
    image: zookeeper
    restart: always
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181

  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "kafka"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_CREATE_TOPICS: "users:1:1:compact"
    depends_on:
      - zookeeper

  consumer:
    container_name: consumer
    build:
      context: ./consumer/
    depends_on:
      - db
      - kafka
    environment:
      SERVICE_NAME: consumer
      MONGODB_URL: mongodb://mongo:27017/epsor
      MONGODB_COLLECTION: users
      KAFKA_BROKER_LIST: kafka:9092

  api:
    container_name: api
    build:
      context: ./api/
    ports:
      - "4000:4000"
    depends_on:
      - db
      - kafka
    environment:
      SERVICE_NAME: api
      SERVICE_PORT: 4000
      MONGODB_URL: mongodb://mongo:27017/epsor
      KAFKA_BROKER_LIST: kafka:9092
